/**
 * @type {import('../schema').Preset}
 */
export const faq = {
  name: 't:names.faq_section',
  category: 't:categories.storytelling',
  blocks: {
    text: {
      type: 'text',
      name: 't:names.heading',
      settings: {
        text: '<h3>Frequently asked questions</h3>',
        type_preset: 'rte',
        font: 'var(--font-body--family)',
        font_size: '',
        line_height: 'normal',
        letter_spacing: 'normal',
        case: 'none',
        wrap: 'pretty',
        width: 'fit-content',
        max_width: 'narrow',
        alignment: 'left',
        'padding-block-start': 0,
        'padding-block-end': 0,
        'padding-inline-start': 0,
        'padding-inline-end': 0,
      },
    },
    accordion: {
      type: 'accordion',
      name: 't:names.accordion',
      settings: {
        icon: 'caret',
        dividers: true,
        type_preset: 'h5',
        inherit_color_scheme: true,
        color_scheme: '',
        border: 'none',
        border_width: 1,
        border_opacity: 100,
        border_radius: 0,
        'padding-block-start': 0,
        'padding-block-end': 0,
        'padding-inline-start': 0,
        'padding-inline-end': 0,
      },
      blocks: {
        accordion_row_1: {
          type: '_accordion-row',
          settings: {
            heading: 'What is the return policy?',
          },
          blocks: {
            text: {
              type: 'text',
              settings: {
                text: '<p>Our goal is for every customer to be totally satisfied with their purchase. If this isn’t the case, let us know and we’ll do our best to work with you to make it right. </p>',

                type_preset: 'rte',
                font: 'var(--font-body--family)',
                font_size: '',
                line_height: 'normal',
                letter_spacing: 'normal',
                case: 'none',
                wrap: 'pretty',
                width: '100%',
                max_width: 'normal',
                alignment: 'left',
                'padding-block-start': 0,
                'padding-block-end': 0,
                'padding-inline-start': 0,
                'padding-inline-end': 0,
              },
            },
          },
          block_order: ['text'],
        },
        accordion_row_2: {
          type: '_accordion-row',
          settings: {
            heading: 'Are any purchases final sale?',
          },
          blocks: {
            text: {
              type: 'text',
              settings: {
                text: '<p>We are unable to accept returns on certain items. These will be carefully marked before purchase.</p>',
                type_preset: 'rte',
                font: 'var(--font-body--family)',
                font_size: '',
                line_height: 'normal',
                letter_spacing: 'normal',
                case: 'none',
                wrap: 'pretty',
                width: '100%',
                max_width: 'normal',
                alignment: 'left',
                'padding-block-start': 0,
                'padding-block-end': 0,
                'padding-inline-start': 0,
                'padding-inline-end': 0,
              },
            },
          },
          block_order: ['text'],
        },
        accordion_row_3: {
          type: '_accordion-row',
          name: 't:names.accordion_dash_row',
          settings: {
            heading: 'When will I get my order?',
          },
          blocks: {
            text: {
              type: 'text',
              name: 't:names.text',
              settings: {
                text: '<p>We will work quickly to ship your order as soon as possible. Once your order has shipped, you will receive an email with further information. Delivery times vary depending on your location.</p>',
                type_preset: 'rte',
                font: 'var(--font-body--family)',
                font_size: '',
                line_height: 'normal',
                letter_spacing: 'normal',
                case: 'none',
                wrap: 'pretty',
                width: '100%',
                max_width: 'normal',
                alignment: 'left',
                'padding-block-start': 0,
                'padding-block-end': 0,
                'padding-inline-start': 0,
                'padding-inline-end': 0,
              },
            },
          },
          block_order: ['text'],
        },
        accordion_row_4: {
          type: '_accordion-row',
          name: 't:names.accordion_dash_row',
          settings: {
            heading: 'Where are your products manufactured?',
          },
          blocks: {
            text: {
              type: 'text',
              name: 't:names.text',
              settings: {
                text: '<p>Our products are manufactured both locally and globally. We carefully select our manufacturing partners to ensure our products are high quality and a fair value. </p>',
                type_preset: 'rte',
                font: 'var(--font-body--family)',
                font_size: '',
                line_height: 'normal',
                letter_spacing: 'normal',
                case: 'none',
                wrap: 'pretty',
                width: '100%',
                max_width: 'normal',
                alignment: 'left',
                'padding-block-start': 0,
                'padding-block-end': 0,
                'padding-inline-start': 0,
                'padding-inline-end': 0,
              },
            },
          },
          block_order: ['text'],
        },
        accordion_row_5: {
          type: '_accordion-row',
          name: 't:names.accordion_dash_row',
          settings: {
            heading: 'How much does shipping cost?',
          },
          blocks: {
            text: {
              type: 'text',
              name: 't:names.text',
              settings: {
                text: '<p>Shipping is calculated based on your location and the items in your order. You will always know the shipping price before you purchase.</p>',
                type_preset: 'rte',
                font: 'var(--font-body--family)',
                font_size: '',
                line_height: 'normal',
                letter_spacing: 'normal',
                case: 'none',
                wrap: 'pretty',
                width: '100%',
                max_width: 'normal',
                alignment: 'left',
                'padding-block-start': 0,
                'padding-block-end': 0,
                'padding-inline-start': 0,
                'padding-inline-end': 0,
              },
            },
          },
          block_order: ['text'],
        },
      },
      block_order: ['accordion_row_1', 'accordion_row_2', 'accordion_row_3', 'accordion_row_4', 'accordion_row_5'],
    },
  },
  block_order: ['text', 'accordion'],
  settings: {
    content_direction: 'column',
    vertical_on_mobile: true,

    horizontal_alignment: 'flex-start',
    vertical_alignment: 'center',
    horizontal_alignment_flex_direction_column: 'flex-start',
    vertical_alignment_flex_direction_column: 'center',
    gap: 32,
    section_width: 'page-width',
    section_height: '',
    color_scheme: '',
    background_media: 'none',
    video_position: 'cover',
    background_image_position: 'cover',
    border: 'none',
    border_width: 1,
    border_opacity: 100,
    border_radius: 0,
    'padding-block-start': 48,
    'padding-block-end': 48,
  },
};
