/**
 * @type {import('../schema').Preset}
 */
export const video = {
  name: 't:names.video_section',
  category: 't:categories.storytelling',
  settings: {
    content_direction: 'column',
    vertical_on_mobile: true,

    horizontal_alignment: 'flex-start',
    vertical_alignment: 'center',
    horizontal_alignment_flex_direction_column: 'flex-start',
    vertical_alignment_flex_direction_column: 'center',
    gap: 16,
    section_width: 'page-width',
    section_height: '',
    color_scheme: '',
    background_media: 'none',

    video_position: 'cover',
    background_image_position: 'cover',
    border: 'none',
    border_width: 1,
    border_opacity: 100,
    border_radius: 0,
    'padding-block-start': 32,
    'padding-block-end': 32,
  },
  blocks: {
    video: {
      type: 'video',
      name: 't:names.video',
      settings: {
        video: '',

        custom_width: 100,
        custom_width_mobile: 100,
        aspect_ratio: '16/9',
        'padding-block-start': 0,
        'padding-block-end': 0,
        'padding-inline-start': 0,
        'padding-inline-end': 0,
      },
    },
    group: {
      type: 'group',
      name: 'Caption',
      settings: {
        content_direction: 'row',
        vertical_on_mobile: true,
        horizontal_alignment: 'space-between',
        vertical_alignment: 'flex-end',
        align_baseline: true,
        horizontal_alignment_flex_direction_column: 'flex-start',
        vertical_alignment_flex_direction_column: 'center',
        gap: 12,
        width: 'fill',
        custom_width: 100,
        width_mobile: 'fill',
        custom_width_mobile: 100,
        height: 'fit',
        custom_height: 100,
        inherit_color_scheme: true,
        color_scheme: '',
        background_media: 'none',
        video_position: 'cover',
        background_image_position: 'cover',
        border: 'none',
        border_width: 1,
        border_opacity: 100,
        border_radius: 0,
        'padding-block-start': 0,
        'padding-block-end': 0,
        'padding-inline-start': 0,
        'padding-inline-end': 0,
      },
      blocks: {
        text: {
          type: 'text',
          name: 't:names.text',
          settings: {
            text: '<p>Take a look behind the scenes of our latest product launch.</p>',
            type_preset: 'rte',
            font: 'var(--font-body--family)',
            font_size: '',
            line_height: 'normal',
            letter_spacing: 'normal',
            case: 'none',
            wrap: 'pretty',
            width: 'fit-content',
            max_width: 'normal',
            alignment: 'left',
            'padding-block-start': 0,
            'padding-block-end': 0,
            'padding-inline-start': 0,
            'padding-inline-end': 0,
          },
        },
        button: {
          type: 'button',
          name: 't:names.button',
          settings: {
            label: 'Discover the collection',
            link: 'shopify://collections/all',
            open_in_new_tab: false,
            style_class: 'link',
            width: 'fit-content',
            custom_width: 100,
            width_mobile: 'fit-content',
            custom_width_mobile: 100,
          },
        },
      },
      block_order: ['text', 'button'],
    },
  },
  block_order: ['video', 'group'],
};
