---

require: rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'berks-cookbooks/**/*'
    - '.idea/**/*'
    - '.git/**/*'
    - '.kitchen/**/*'
    - '*.lock'
    - 'vendor/**/*'
    - 'tmp/**/*'

Layout/CaseIndentation:
  IndentOneStep: false

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false
  # Max: 256

Layout/ParameterAlignment:
  Enabled: false

# New Cop add 1.22 and Seems to be broke
Lint/RequireRelativeSelfPath:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Max: 256

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 256
  CountComments: false

Metrics/ModuleLength:
  Max: 512
  CountComments: false

Metrics/PerceivedComplexity:
  Max: 30

Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise
