MatchingTranslations:
  enabled: false
TemplateLength:
  enabled: false

ignore:
  # any file whose name contains "replo"
  - "**/*replo*"
  # any file whose name contains "bloggle"
  - "**/*bloggle*"