MatchingTranslations:
  enabled: false
TemplateLength:
  enabled: false
ignore:
  - "sections/zeno-*.liquid"
  - "snippets/zeno-page-*"
  - "templates/*zeno*.liquid"
  - "layout/theme.zeno.fullscreen.liquid"