---
MatchingTranslations:
  enabled: false
TemplateLength:
  enabled: false

# ignore:
#   - assets/
#   - snippets/old-*

UnknownFilter:
  enabled: false
NestedSnippet:
  enabled: false
NestedTemplate:
  enabled: false
PaginationSize:
  enabled: false
SchemaJsonFormat:
  enabled: false
AssetPreload:
  enabled: false
