---
MatchingTranslations:
  enabled: false
TemplateLength:
  enabled: false

# ignore:
#   - assets/
#   - snippets/old-*

AssetPreload:
  enabled: false
ImgLazyLoading:
  enabled: false
NestedSnippet:
  enabled: false
NestedTemplate:
  enabled: false
LiquidTag:
  enabled: false
PaginationSize:
  enabled: false
SchemaJsonFormat:
  enabled: false
UnknownFilter:
  enabled: false
