version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - autocorrect
  - cicd
  - Customizer
  - levelname
  - Levon
  - makerlab
  - Makerworld
  - Openscad
  - pyinvoke
  - pylint
  - pylintrc
  - pythonopenscad
  - rcfile
  - rubocop
  - solidpython
  - strout
  - venv
ignoreWords: []
import: []
