module.exports = {
  extends: './stylelint.config.js',
  rules: {
    'plugin/no-unsupported-browser-features': [
      true,
      {
        severity: 'error',
        ignore: [
          'css-nesting',
          'css-relative-colors',
          'text-decoration',
          'intrinsic-width',
          'css-scrollbar',
          'css3-cursors',
          'css3-cursors-newer',
          'css-content-visibility',
          'css-display-contents',
          'css-text-box-trim',
          'css-resize',
          'multicolumn',
          'css-mixblendmode',
          'css-container-queries-style',
        ],
      },
    ],
    'no-descending-specificity': null,
    'selector-max-specificity': null,
    'comment-whitespace-inside': null,
    'declaration-empty-line-before': null,
    'rule-empty-line-before': null,
    'value-keyword-case': null,
    'comment-empty-line-before': null,
    'no-duplicate-selectors': null,
    'color-function-notation': null,
    'alpha-value-notation': null,
    'shorthand-property-no-redundant-values': null,
    'custom-property-empty-line-before': null,
    'declaration-block-no-duplicate-properties': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'selector-not-notation': null,
    'keyframes-name-pattern': null,
    'at-rule-empty-line-before': null,
    'selector-pseudo-element-colon-notation': null,
    'selector-id-pattern': null,
  },
};
