/**
 * @type {import('../schema').Schema}
 */
export default {
  name: 't:names.logo',
  tag: null,
  class: 'header-logo',
  settings: [
    {
      type: 'paragraph',
      content: 't:content.edit_logo_in_theme_settings',
    },
    {
      type: 'header',
      content: 't:content.visibility',
    },
    {
      type: 'checkbox',
      id: 'hide_logo_on_home_page',
      label: 't:settings.hide_logo_on_home_page',
    },
    {
      type: 'header',
      content: 't:content.size',
      visible_if: '{{ settings.logo != blank }}',
    },
    {
      type: 'range',
      id: 'custom_height',
      label: 't:settings.desktop_height',
      min: 12,
      max: 100,
      step: 1,
      unit: 'px',
      default: 20,
      visible_if: '{{ settings.logo != blank }}',
    },
    {
      type: 'range',
      id: 'custom_height_mobile',
      label: 't:settings.mobile_height',
      min: 12,
      max: 100,
      step: 1,
      unit: 'px',
      default: 20,
      visible_if: '{{ settings.logo != blank }}',
    },
    {
      type: 'header',
      content: 't:content.padding_desktop',
    },
    {
      type: 'range',
      id: 'padding-block-start',
      label: 't:settings.top',
      min: 0,
      max: 100,
      step: 1,
      unit: 'px',
      default: 0,
    },
    {
      type: 'range',
      id: 'padding-block-end',
      label: 't:settings.bottom',
      min: 0,
      max: 100,
      step: 1,
      unit: 'px',
      default: 0,
    },
    {
      type: 'range',
      id: 'padding-inline-start',
      label: 't:settings.left',
      min: 0,
      max: 100,
      step: 1,
      unit: 'px',
      default: 0,
    },
    {
      type: 'range',
      id: 'padding-inline-end',
      label: 't:settings.right',
      min: 0,
      max: 100,
      step: 1,
      unit: 'px',
      default: 0,
    },
  ],
};
