/**
 * @type {import('../schema').Schema}
 */
export default {
  name: 't:names.filters',
  tag: null,
  settings: [
    {
      type: 'checkbox',
      id: 'enable_filtering',
      label: 't:settings.enable_filtering',
      info: 't:info.enable_filtering_info',
      default: false,
    },
    {
      type: 'select',
      id: 'filter_style',
      label: 't:settings.direction',
      options: [
        {
          value: 'horizontal',
          label: 't:options.horizontal',
        },
        {
          value: 'vertical',
          label: 't:options.vertical',
        },
      ],
      default: 'horizontal',
      visible_if: '{{ block.settings.enable_filtering == true }}',
    },
    {
      type: 'select',
      id: 'filter_width',
      label: 't:settings.width',
      options: [
        {
          value: 'centered',
          label: 't:options.page',
        },
        {
          value: 'full-width',
          label: 't:options.full',
        },
      ],
      default: 'centered',
      visible_if: "{{ block.settings.enable_filtering == true and block.settings.filter_style == 'horizontal' }}",
    },
    {
      type: 'select',
      id: 'text_label_case',
      label: 't:settings.text_label_case',
      options: [
        {
          value: 'default',
          label: 't:options.default',
        },
        {
          value: 'uppercase',
          label: 't:options.uppercase',
        },
      ],
      default: 'default',
      visible_if: '{{ block.settings.enable_filtering == true }}',
    },
    {
      type: 'checkbox',
      id: 'show_swatch_label',
      label: 't:settings.show_swatch_label',
      default: false,
      visible_if: '{{ block.settings.enable_filtering == true }}',
    },
    {
      type: 'checkbox',
      id: 'show_filter_label',
      label: 't:settings.show_filter_label',
      default: false,
      visible_if: '{{ block.settings.enable_filtering == true }}',
    },
    {
      type: 'checkbox',
      id: 'enable_sorting',
      label: 't:settings.enable_sorting',
      default: true,
    },
    {
      type: 'checkbox',
      id: 'enable_grid_density',
      label: 't:settings.enable_grid_density',
      default: true,
    },
    {
      type: 'checkbox',
      id: 'inherit_color_scheme',
      label: 't:settings.inherit_color_scheme',
      default: true,
    },
    {
      type: 'color_scheme',
      id: 'color_scheme',
      label: 't:settings.color_scheme',
      default: 'scheme-1',
      visible_if: '{{ block.settings.inherit_color_scheme == false }}',
    },
    {
      type: 'header',
      content: 't:content.padding',
    },
    {
      type: 'range',
      id: 'padding-block-start',
      label: 't:settings.top',
      min: 0,
      max: 100,
      step: 1,
      unit: 'px',
      default: 0,
    },
    {
      type: 'range',
      id: 'padding-block-end',
      label: 't:settings.bottom',
      min: 0,
      max: 100,
      step: 1,
      unit: 'px',
      default: 0,
    },
    {
      type: 'range',
      id: 'padding-inline-start',
      label: 't:settings.left',
      min: 0,
      max: 100,
      step: 1,
      unit: 'px',
      default: 0,
    },
    {
      type: 'range',
      id: 'padding-inline-end',
      label: 't:settings.right',
      min: 0,
      max: 100,
      step: 1,
      unit: 'px',
      default: 0,
    },
    {
      type: 'header',
      content: 't:content.margin',
    },
    {
      type: 'range',
      id: 'facets_margin_bottom',
      label: 't:settings.bottom',
      min: 0,
      max: 100,
      step: 1,
      unit: 'px',
      default: 8,
      visible_if: "{{ block.settings.filter_style == 'horizontal' }}",
    },
    {
      type: 'range',
      id: 'facets_margin_right',
      label: 't:settings.right',
      min: 0,
      max: 100,
      step: 1,
      unit: 'px',
      default: 20,
      visible_if: "{{ block.settings.filter_style == 'vertical' }}",
    },
  ],
};
