export default {
    data: function () {
        return {
            finelinesorwrinkles: {
                'title':"Fine lines and wrinkles",
                'display':true,
                'clinical_percent': false,
                'clinical_text':"The routine provides a bright, radiant complexion.*",
                'description':"In an independent clinical study, 81% of people reported a bright, radiant complexion with PROVEN's personalized regime.*",
                'img_after':"http://d201v9s59ezpea.cloudfront.net/finelines2.jpg",
                'img_before':"http://d201v9s59ezpea.cloudfront.net/finelines1.jpg",
            },
            acne: {
                'title':"Acne",
                'display':true,
                'clinical_percent': 81,
                'clinical_text':"The routine provides a bright, radiant complexion.*",
                'description':"In an independent clinical study, 81% of people reported a bright, radiant complexion with PROVEN's personalized regime.*",
                'img_after':"http://d201v9s59ezpea.cloudfront.net/acne2.jpg",
                'img_before':"http://d201v9s59ezpea.cloudfront.net/acne1.jpg",
            },
            lossoffirmnessorelasticity: {
                'title': 'Firmness and elasticity loss',
                'display':true,
                'clinical_percent': 81,
                'clinical_text':"The routine provides a bright, radiant complexion.*",
                'description':"In an independent clinical study, 81% of people reported a bright, radiant complexion with PROVEN's personalized regime.*",
                'img_after':"http://d201v9s59ezpea.cloudfront.net/skintight2.jpg",
                'img_before':"http://d201v9s59ezpea.cloudfront.net/skintight1.jpg",
            },
            redness: {
                'title': 'Redness',
                'display':true,
                'clinical_percent': 81,
                'clinical_text':"The routine provides a bright, radiant complexion.*",
                'description':"In an independent clinical study, 81% of people reported a bright, radiant complexion with PROVEN's personalized regime.*",
                'img_after':"http://d201v9s59ezpea.cloudfront.net/redness2.jpg",
                'img_before':"http://d201v9s59ezpea.cloudfront.net/redness1.jpg",
            },
            sensitivity: {
                'title': 'Sensitivity',
                'display':true,
                'clinical_percent': 81,
                'clinical_text':"The routine provides a bright, radiant complexion.*",
                'description':"In an independent clinical study, 81% of people reported a bright, radiant complexion with PROVEN's personalized regime.*",
                'img_after':"http://d201v9s59ezpea.cloudfront.net/sensitivity2.jpg",
                'img_before':"http://d201v9s59ezpea.cloudfront.net/sensitivity1.jpg"
            },
            hyperpigmentation: {
                'display':true,
                'clinical_percent': 81,
                'clinical_text':"The routine provides a bright, radiant complexion.*",
                'description':"In an independent clinical study, 81% of people reported a bright, radiant complexion with PROVEN's personalized regime.*",
                'img_after':"http://d201v9s59ezpea.cloudfront.net/hyperpigmentation2.jpg",
                'img_before':"http://d201v9s59ezpea.cloudfront.net/hyperpigmentation1.jpg",
            },
            seborrhoeicdermatitis: {
                'title':"Seborrhoeic Dermatitis",
                'display':false,
                'clinical_percent': 81,
                'clinical_text':"The routine provides a bright, radiant complexion.*",
                'description':"In an independent clinical study, 81% of people reported a bright, radiant complexion with PROVEN's personalized regime.*",
                'img_after':false,
                'img_before':false,
            },
            facialpsoriasis: {
                'title':"Facial Psoriasis",
                'display':false,
                'clinical_percent': 81,
                'clinical_text':"The routine provides a bright, radiant complexion.*",
                'description':"In an independent clinical study, 81% of people reported a bright, radiant complexion with PROVEN's personalized regime.*",
                'img_after':false,
                'img_before':false,
            },
            eczemaatopicdermatitis: {
                'title':"Eczema/Atopic Dermatitis",
                'display':false,
                'clinical_percent': 81,
                'clinical_text':"The routine provides a bright, radiant complexion.*",
                'description':"In an independent clinical study, 81% of people reported a bright, radiant complexion with PROVEN's personalized regime.*",
                'img_after':false,
                'img_before':false,
            },
            rosacea: {
                'title': 'Rosacea',
                'display':true,
                'clinical_percent': 81,
                'clinical_text':"The routine provides a bright, radiant complexion.*",
                'description':"In an independent clinical study, 81% of people reported a bright, radiant complexion with PROVEN's personalized regime.*",
                'img_after':"http://d201v9s59ezpea.cloudfront.net/rosacea2.jpg",
                'img_before':"http://d201v9s59ezpea.cloudfront.net/rosacea1.jpg",
            },
        }
    }
};