---
name: Test / Style

on: [push, pull_request]

jobs:
  # https://github.com/arthurnn/code-scanning-rubocop
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          # runs 'bundle install' and caches installed gems automatically
          # ruby-version: 3.4.3 - uses .ruby-version file

      - name: Rubocop
        run: bundle exec rubocop --display-cop-names

  theme-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Install theme-check
        run: gem install theme-check

      - name: Run theme-check
        run: theme-check .

  yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Yaml Lint
        uses: bewuethr/yamllint-action@v1
        with:
          config-file: .yamllint
